# See https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
comment_width = 75
format_code_in_doc_comments = true
max_width = 75
normalize_doc_attributes = true
wrap_comments = true
imports_granularity = "Crate"
imports_layout = "mixed"
edition = "2021"
